# Generated by Django 3.1 on 2020-12-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('kind', models.IntegerField(choices=[(0, 'NONE'), (1, 'DONE'), (2, 'CLAIMED'), (3, 'PROPOSED')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
