# Generated by Django 3.1 on 2021-01-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_auto_20210113_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskclaimrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='taskclaimrequest',
            name='kind',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='taskclaim',
            name='kind',
            field=models.IntegerField(choices=[(0, 'Done'), (1, 'Active'), (2, 'Failed')], default=0),
        ),
    ]
