# Generated by Django 3.1 on 2021-02-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_auto_20210114_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskclaim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskclaimrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
