# Generated by Django 3.1 on 2021-02-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_auto_20210216_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskclaimrequest',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
