# Generated by Django 3.1 on 2021-06-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0033_user_model'),
        ('matching', '0010_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDeliveryAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDeliveryAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('kind', models.IntegerField(choices=[(0, 'New'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('is_canceled', models.BooleanField(default=False)),
                ('delivery_message', models.CharField(default=None, max_length=255)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='taskclaim',
            name='kind',
            field=models.IntegerField(choices=[(0, 'Done'), (1, 'Active'), (2, 'Failed'), (3, 'In review')], default=0),
        ),
        migrations.DeleteModel(
            name='TaskClaimRequest',
        ),
        migrations.AddField(
            model_name='taskdeliveryattempt',
            name='task_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.taskclaim'),
        ),
        migrations.AddField(
            model_name='taskdeliveryattachment',
            name='task_delivery_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='matching.taskdeliveryattempt'),
        ),
    ]
