# Generated by Django 3.1 on 2022-06-18 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0013_auto_20220113_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('kind', models.IntegerField(choices=[(0, 'Done'), (1, 'Active'), (2, 'Failed'), (3, 'In review')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BountyDeliveryAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BountyDeliveryAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('kind', models.IntegerField(choices=[(0, 'New'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('is_canceled', models.BooleanField(default=False)),
                ('delivery_message', models.CharField(default=None, max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
