# Generated by Django 3.1 on 2022-06-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0098_auto_20220618_2252'),
        ('matching', '0015_auto_20220618_2252'),
        ('talent', '0046_personpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='bountyclaim',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.bounty'),
        ),
        migrations.AddField(
            model_name='bountyclaim',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.person'),
        ),        
    ]
