# Generated by Django 3.1 on 2022-06-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0017_auto_20220619_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskclaim',
            name='person',
        ),
        migrations.RemoveField(
            model_name='taskclaim',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskdeliveryattachment',
            name='task_delivery_attempt',
        ),
        migrations.RemoveField(
            model_name='taskdeliveryattempt',
            name='person',
        ),
        migrations.RemoveField(
            model_name='taskdeliveryattempt',
            name='task_claim',
        ),
        migrations.DeleteModel(
            name='TaskClaim',
        ),
        migrations.DeleteModel(
            name='TaskDeliveryAttachment',
        ),
        migrations.DeleteModel(
            name='TaskDeliveryAttempt',
        ),
    ]
