# Generated by Django 3.1 on 2022-08-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0018_auto_20220623_0240'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "SELECT setval(pg_get_serial_sequence('\"matching_bountyclaim\"','id'), coalesce(max(\"id\"), 1), max(\"id\") IS NOT null) FROM \"matching_bountyclaim\";",
                "SELECT setval(pg_get_serial_sequence('\"matching_bountydeliveryattempt\"','id'), coalesce(max(\"id\"), 1), max(\"id\") IS NOT null) FROM \"matching_bountydeliveryattempt\";",
                "SELECT setval(pg_get_serial_sequence('\"matching_bountydeliveryattachment\"','id'), coalesce(max(\"id\"), 1), max(\"id\") IS NOT null) FROM \"matching_bountydeliveryattachment\";"
            ],
            reverse_sql=[],
        )
    ]
