# Generated by Django 3.1 on 2021-10-31 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0044_personskill_category_alter'),
        ('work', '0089_constraints_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_content', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_contributor_agreement', to='work.product')),
            ],
            options={
                'db_table': 'contribution_management_contributor_agreement',
            },
        ),
        migrations.CreateModel(
            name='ContributorGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_contributor_guide', to='work.product')),
            ],
        ),
        migrations.CreateModel(
            name='ContributorAgreementAcceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contribution_management.contributoragreement')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_contributor_agreement_acceptance', to='talent.person')),
            ],
            options={
                'db_table': 'contribution_management_contributor_agreement_acceptance',
            },
        ),
    ]
