# Generated by Django 3.1 on 2022-02-18 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0097_auto_20211225_2230'),
        ('contribution_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributorguide',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_contributor_guide', to='work.taskcategory'),
        ),
    ]
