# Generated by Django 3.1 on 2021-04-01 11:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0029_person_user'),
        ('ideas_bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_type',
            field=models.BooleanField(default=False, verbose_name='Is this bug security related?'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.TextField(verbose_name='Please describe the Bug'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='headline',
            field=models.CharField(max_length=80, verbose_name='Please give your bug a name'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(verbose_name='Please describe your idea'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='headline',
            field=models.CharField(max_length=80, verbose_name='Please give your idea a name'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_type',
            field=models.IntegerField(choices=[(0, 'Product Tweak'), (1, 'New Feature'), (2, 'New Capability'), (3, 'Non-Functional Improvement'), (4, 'Other')], verbose_name='Which of the following best matches your idea?'),
        ),
        migrations.CreateModel(
            name='IdeaVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('vote_type', models.IntegerField(choices=[(0, 'Up'), (1, 'Down')])),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_bugs.idea')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BugVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('vote_type', models.IntegerField(choices=[(0, 'Up'), (1, 'Down')])),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_bugs.bug')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
