# Generated by Django 3.1 on 2021-04-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0019_auto_20210402_0837'),
        ('ideas_bugs', '0002_auto_20210401_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='comments_start',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.bugcomment'),
        ),
        migrations.AddField(
            model_name='idea',
            name='comments_start',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.ideacomment'),
        ),
    ]
