# Generated by Django 3.1 on 2021-04-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_bugs', '0003_auto_20210402_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='status',
            field=models.IntegerField(choices=[(0, 'Submitted'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Resolved')], default=0),
        ),
        migrations.AddField(
            model_name='idea',
            name='status',
            field=models.IntegerField(choices=[(0, 'Submitted'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Resolved')], default=0),
        ),
        migrations.CreateModel(
            name='IdeaStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Resolved')])),
                ('current_status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Resolved')])),
                ('description', models.TextField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_bugs.idea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BugStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Resolved')])),
                ('current_status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Resolved')])),
                ('description', models.TextField()),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_bugs.bug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
