# Generated by Django 3.1 on 2021-04-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0030_auto_20210402_1312'),
        ('ideas_bugs', '0004_auto_20210406_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugstatushistory',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.person'),
        ),
        migrations.AddField(
            model_name='ideastatushistory',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.person'),
        ),
    ]
