# Generated by Django 3.1 on 2021-04-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_bugs', '0005_auto_20210406_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Product Tweak'), (1, 'New Feature'), (2, 'New Capability'), (3, 'Non-Functional Improvement'), (4, 'Other')], default=None, null=True, verbose_name='Which of the following best matches your idea?'),
        ),
    ]
