# Generated by Django 3.1 on 2021-06-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_bugs', '0008_user_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='customer_person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='bugstatushistory',
            old_name='customer_person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='bugvote',
            old_name='customer_person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='customer_person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='ideastatushistory',
            old_name='customer_person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='ideavote',
            old_name='customer_person',
            new_name='person',
        ),
    ]
