version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.1-buster  # primary container for the build job
    steps:
      - checkout # check out the code in the project directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install -r requirements/test.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.9/site-packages"
      - run: |
            python manage.py collectstatic --noinput
            pytest
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
          destination: tr1
