# Generated by Django 3.1 on 2020-12-30 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_task_tag'),
        ('talent', '0002_auto_20201226_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.initiative'),
        ),
    ]
