# Generated by Django 3.1 on 2021-01-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0006_auto_20210109_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productperson',
            name='right',
            field=models.IntegerField(choices=[(0, 'NONE'), (1, 'ADMIN'), (2, 'MANAGER'), (3, 'CONTRIBUTOR'), (4, 'WATCHER')], default=0),
        ),
    ]
