# Generated by Django 3.1 on 2021-01-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0007_auto_20210114_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productperson',
            name='right',
            field=models.IntegerField(choices=[(0, 'Watcher'), (1, 'Admin'), (2, 'Manager'), (3, 'Contributor')], default=0),
        ),
    ]
