# Generated by Django 3.1 on 2021-02-04 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_auto_20210203_1349'),
        ('talent', '0010_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.organisation'),
        ),
    ]
