# Generated by Django 3.1 on 2021-02-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0011_owner_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='organisation',
        ),
    ]
