# Generated by Django 3.1 on 2021-02-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0012_remove_owner_organisation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
