# Generated by Django 3.1 on 2021-02-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0014_personsocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='headline',
            field=models.CharField(default='CTO @LeasePlan. Entrepreneur - AuthMachine, Two Player Chess', max_length=255),
        ),
    ]
