# Generated by Django 3.1 on 2021-02-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0015_person_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='headline',
            field=models.CharField(max_length=255),
        ),
    ]
