# Generated by Django 3.1 on 2021-02-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0016_auto_20210210_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personprofile',
            name='rank',
        ),
    ]
