# Generated by Django 3.1 on 2021-03-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0019_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
