# Generated by Django 3.1 on 2021-03-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0021_person_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
