# Generated by Django 3.1 on 2021-03-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0021_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productperson',
            name='right',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Product Admin'), (2, 'Product Manager'), (3, 'Contributor'), (4, 'Super Admin')], default=0),
        ),
    ]
