# Generated by Django 3.1 on 2021-03-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0022_auto_20210304_1302'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table=None,
        ),
    ]
