# Generated by Django 3.1 on 2021-03-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0023_auto_20210304_1303'),
        ('talent', '0022_auto_20210304_1121'),
    ]

    operations = [
    ]
