# Generated by Django 3.1 on 2021-03-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0024_merge_20210305_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='test_user',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
