# Generated by Django 3.1 on 2021-03-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('talent', '0027_auto_20210330_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.username'),
        ),
    ]
