# Generated by Django 3.1 on 2021-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0029_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='headline',
            field=models.TextField(),
        ),
    ]
