# Generated by Django 3.1 on 2021-06-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0031_user_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personprofile',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personsocial',
            name='person',
        ),
        migrations.RemoveField(
            model_name='productperson',
            name='person',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='review',
            name='person',
        ),
        migrations.AddField(
            model_name='personprofile',
            name='customer_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.person'),
        ),
        migrations.AddField(
            model_name='personsocial',
            name='customer_person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='talent.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productperson',
            name='customer_person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='talent.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='created_by_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given', to='talent.person'),
        ),
        migrations.AddField(
            model_name='review',
            name='customer_person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='talent.person'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AuthorizedUser',
        ),
    ]
