# Generated by Django 3.1 on 2021-06-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0033_user_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='user',
        ),
    ]
