# Generated by Django 3.1 on 2021-06-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0035_social_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('expertise', models.CharField(blank=True, max_length=300)),
                ('person_profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.personprofile')),
            ],
        ),
    ]
