# Generated by Django 3.1 on 2021-07-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0036_person_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='personprofile',
            name='avatar',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.personavatar'),
        ),
    ]
