# Generated by Django 3.1 on 2021-07-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0037_person_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personskill',
            name='expertise',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
