# Generated by Django 3.1 on 2021-07-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0038_person_skill_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personprofile',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='talent.person'),
        ),
        migrations.AlterField(
            model_name='personskill',
            name='person_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='talent.personprofile'),
        ),
        migrations.CreateModel(
            name='PersonWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(0, 'Personal'), (1, 'Company')], max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='talent.personprofile')),
            ],
        ),
    ]
