# Generated by Django 3.1 on 2021-07-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0040_person_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personwebsite',
            name='type',
            field=models.IntegerField(choices=[(0, 'Personal'), (1, 'Company')]),
        ),
    ]
