# Generated by Django 3.1 on 2021-07-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0041_changes_for_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personwebsite',
            name='person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='talent.personprofile'),
        ),
    ]
