# Generated by Django 3.1 on 2021-08-03 14:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0042_constraints_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personskill',
            name='expertise',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
