# Generated by Django 3.1 on 2022-01-21 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0045_auto_20211231_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_me_challenges', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='talent.person')),
            ],
        ),
    ]
