# Generated by Django 3.1 on 2020-12-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='task_tags', to='work.Tag'),
        ),
    ]
