# Generated by Django 3.1 on 2021-01-07 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_task_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 1, 7, 17, 47, 10, 180629, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
