# Generated by Django 3.1 on 2021-01-12 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20210109_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repository',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CodeRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.product')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.task')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
