# Generated by Django 3.1 on 2021-01-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20210112_0728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coderepository',
            options={'verbose_name_plural': 'CodeRepositories'},
        ),
    ]
