# Generated by Django 3.1 on 2021-01-12 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20210112_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='repository',
        ),
        migrations.AddField(
            model_name='coderepository',
            name='git_access_token',
            field=models.CharField(default=datetime.datetime(2021, 1, 12, 11, 10, 17, 482532, tzinfo=utc), max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coderepository',
            name='git_owner',
            field=models.CharField(default=datetime.datetime(2021, 1, 12, 11, 10, 23, 362908, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coderepository',
            name='repository',
            field=models.URLField(blank=True, null=True),
        ),
    ]
