# Generated by Django 3.1 on 2021-01-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_auto_20210113_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Completed')], default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
