# Generated by Django 3.1 on 2021-01-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_auto_20210114_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coderepository',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='repository',
            field=models.URLField(blank=True, null=True),
        ),
    ]
