# Generated by Django 3.1 on 2021-01-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_auto_20210114_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Completed')], default=1),
        ),
    ]
