# Generated by Django 3.1 on 2021-01-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_auto_20210117_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='path',
            field=models.URLField(),
        ),
    ]
