# Generated by Django 3.1 on 2021-01-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_auto_20210118_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
    ]
