# Generated by Django 3.1 on 2021-01-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0018_auto_20210118_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='capability',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(),
        ),
    ]
