# Generated by Django 3.1 on 2021-01-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0019_auto_20210121_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(),
        ),
    ]
