# Generated by Django 3.1 on 2021-01-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_auto_20210121_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='website',
            field=models.CharField(max_length=512),
        ),
    ]
