# Generated by Django 3.1 on 2021-01-22 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0022_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='short_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
