# Generated by Django 3.1 on 2021-01-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0023_task_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
