# Generated by Django 3.1 on 2021-02-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0007_customeraccount_plan'),
        ('work', '0024_auto_20210123_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.owner'),
        ),
    ]
