# Generated by Django 3.1 on 2021-02-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0027_capabilitynode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityNodeAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.attachment')),
                ('capability_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.capabilitynode')),
            ],
        ),
    ]
