# Generated by Django 3.1 on 2021-02-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0028_capabilitynodeattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capabilitynode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='capabilitynode',
            name='updated_at',
        ),
    ]
