# Generated by Django 3.1 on 2021-02-16 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0030_auto_20210216_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capability_start_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.capabilitynode'),
        ),
    ]
