# Generated by Django 3.1 on 2021-02-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0031_product_capability_start_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='capability_start_id',
            new_name='capability_start',
        ),
    ]
