# Generated by Django 3.1 on 2021-02-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0032_auto_20210216_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capabilitynode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='capabilitynode',
            name='updated_at',
        ),
    ]
