# Generated by Django 3.1 on 2021-02-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0037_auto_20210218_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capabilityattachment',
            old_name='capability_node',
            new_name='capability',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='capability_node',
            new_name='capability',
        ),
    ]
