# Generated by Django 3.1 on 2021-02-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0039_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='priority',
            field=models.IntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')], default=1),
        ),
    ]
