# Generated by Django 3.1 on 2021-02-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0040_initiative_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='priority',
        ),
    ]
