# Generated by Django 3.1 on 2021-02-25 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0018_auto_20210216_1537'),
        ('work', '0041_remove_initiative_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.person'),
        ),
    ]
