# Generated by Django 3.1 on 2021-02-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0042_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
