# Generated by Django 3.1 on 2021-03-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0043_remove_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='published_id',
            field=models.IntegerField(default=10),
        ),
    ]
