# Generated by Django 3.1 on 2021-03-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0044_task_published_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='published_id',
            field=models.IntegerField(default=0),
        ),
    ]
