# Generated by Django 3.1 on 2021-03-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0045_auto_20210301_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto_approve_task_claims',
            field=models.BooleanField(default=True),
        ),
    ]
