# Generated by Django 3.1 on 2021-03-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0047_auto_20210302_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='depend_on',
            field=models.ManyToManyField(blank=True, related_name='_task_depend_on_+', to='work.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Blocked'), (2, 'Available'), (3, 'Claimed'), (4, 'Done')], default=0),
        ),
    ]
