# Generated by Django 3.1 on 2021-03-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0048_task_comments_start'),
        ('work', '0048_auto_20210305_0813'),
    ]

    operations = [
    ]
