# Generated by Django 3.1 on 2021-03-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0017_auto_20210305_1122'),
        ('work', '0049_merge_20210305_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments_start',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
    ]
