# Generated by Django 3.1 on 2021-03-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0024_merge_20210305_1122'),
        ('work', '0050_auto_20210305_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.person'),
        ),
        migrations.AlterField(
            model_name='product',
            name='capability_start',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.capability'),
        ),
        migrations.AlterField(
            model_name='task',
            name='published_id',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
