# Generated by Django 3.1 on 2021-03-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0024_merge_20210305_1122'),
        ('work', '0051_auto_20210308_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='task',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.person'),
        ),
    ]
