# Generated by Django 3.1 on 2021-03-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0054_taskdepend'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taskdepend',
            table='work_task_depend',
        ),
    ]
