# Generated by Django 3.1 on 2021-03-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0055_auto_20210309_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capability',
            name='uuid',
        ),
    ]
