# Generated by Django 3.1 on 2021-03-11 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0056_remove_capability_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='capability',
            name='video_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CapabilityStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.capability')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.stack')),
            ],
        ),
    ]
