# Generated by Django 3.1 on 2021-03-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0057_auto_20210311_1119'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='capabilitystack',
            table='capability_stack',
        ),
    ]
