# Generated by Django 3.1 on 2021-03-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0058_auto_20210311_1120'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='capability',
            table='capability',
        ),
        migrations.AlterModelTable(
            name='capabilityattachment',
            table='capability_attachment',
        ),
    ]
