# Generated by Django 3.1 on 2021-03-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0059_auto_20210311_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='detail_url',
        ),
        migrations.RemoveField(
            model_name='task',
            name='repository',
        ),
        migrations.AddField(
            model_name='task',
            name='target_work_location',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='short_description',
            field=models.TextField(max_length=256),
        ),
    ]
