# Generated by Django 3.1 on 2021-03-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0062_remove_product_tag'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producttag',
            table='work_product_tag',
        ),
    ]
