# Generated by Django 3.1 on 2021-03-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0063_auto_20210316_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
