# Generated by Django 3.1 on 2021-03-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0026_socialaccount'),
        ('comments', '0018_auto_20210305_1508'),
        ('work', '0064_delete_producttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='capability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.capability'),
        ),
        migrations.AlterField(
            model_name='task',
            name='comments_start',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.initiative'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.person'),
        ),
    ]
