# Generated by Django 3.1 on 2021-03-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0065_auto_20210318_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
