# Generated by Django 3.1 on 2021-03-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0066_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
