# Generated by Django 3.1 on 2021-04-05 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0020_capabilitycomment'),
        ('work', '0067_product_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='capability',
            name='comments_start',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.capabilitycomment'),
        ),
    ]
