# Generated by Django 3.1 on 2021-04-13 14:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0030_auto_20210402_1312'),
        ('work', '0071_tasklisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklisting',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.person'),
        ),
        migrations.AddField(
            model_name='tasklisting',
            name='product_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tasklisting',
            name='assign_to',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tasklisting',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.product'),
        ),
        migrations.AlterField(
            model_name='tasklisting',
            name='reviewer',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tasklisting',
            name='stacks',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='tasklisting',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='tasklisting',
            name='task_claim',
            field=models.JSONField(null=True),
        ),
    ]
