# Generated by Django 3.1 on 2021-04-14 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0073_auto_20210413_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklisting',
            name='initiative_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='tasklisting',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.initiative'),
        ),
    ]
