# Generated by Django 3.1 on 2021-04-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0075_auto_20210414_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklisting',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work.task'),
        ),
    ]
