# Generated by Django 3.1 on 2021-04-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0076_auto_20210414_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='target_work_location',
        ),
        migrations.RemoveField(
            model_name='tasklisting',
            name='target_work_location',
        ),
    ]
