# Generated by Django 3.1 on 2021-04-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0077_auto_20210416_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklisting',
            name='in_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='stack',
            field=models.ManyToManyField(blank=True, related_name='task_stacks', to='work.Stack', verbose_name='Skills Required'),
        ),
    ]
