# Generated by Django 3.1 on 2021-04-22 12:49

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0030_auto_20210402_1312'),
        ('work', '0078_auto_20210420_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateProductRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('photo', models.URLField(blank=True, default=None, null=True)),
                ('name', models.TextField()),
                ('short_description', models.TextField()),
                ('full_description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(max_length=512)),
                ('detail_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_private', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Accepted'), (1, 'New'), (2, 'Declined')], default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.person')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
