# Generated by Django 3.1 on 2021-04-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0080_auto_20210422_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklisting',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capability',
            name='video_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
