# Generated by Django 3.1 on 2021-04-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0081_auto_20210427_0816'),
    ]

