# Generated by Django 3.1 on 2021-06-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0032_user_model'),
        ('work', '0082_task_contribution_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createproductrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tasklisting',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='tasklisting',
            name='creator',
        ),
        migrations.AddField(
            model_name='createproductrequest',
            name='created_by_person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='talent.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasklisting',
            name='assigned_to_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='talent.person'),
        ),
        migrations.AddField(
            model_name='tasklisting',
            name='task_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='talent.person'),
        ),
    ]
