# Generated by Django 3.1 on 2021-06-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0032_user_model'),
        ('work', '0083_user_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='task',
            name='created_by_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='talent.person'),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewer_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.person'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='talent.person'),
        ),
    ]
