# Generated by Django 3.1 on 2021-06-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0085_user_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Blocked'), (2, 'Available'), (3, 'Claimed'), (4, 'Done'), (5, 'In review')], default=0),
        ),
        migrations.AlterField(
            model_name='tasklisting',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Blocked'), (2, 'Available'), (3, 'Claimed'), (4, 'Done'), (5, 'In review')], default=0),
        ),
    ]
