# Generated by Django 3.1 on 2021-07-06 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0087_task_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategorylist',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='work.taskcategorylist'),
        ),
    ]
