# Generated by Django 3.1 on 2021-11-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0091_auto_20211125_0947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskCategoryList',
            new_name='TaskCategory',
        ),
    ]
