# Generated by Django 3.1 on 2021-12-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0096_auto_20211225_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capability',
            options={'verbose_name_plural': 'capabilities'},
        ),
    ]
