# Generated by Django 3.1 on 2022-06-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0099_auto_20220619_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='capability',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='comments_start',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contribution_guide',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='task',
            name='initiative',
        ),
        migrations.RemoveField(
            model_name='task',
            name='product',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='taskdepend',
            name='depends_by',
        ),
        migrations.RemoveField(
            model_name='taskdepend',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasklisting',
            name='assigned_to_person',
        ),
        migrations.RemoveField(
            model_name='tasklisting',
            name='capability',
        ),
        migrations.RemoveField(
            model_name='tasklisting',
            name='initiative',
        ),
        migrations.RemoveField(
            model_name='tasklisting',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tasklisting',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasklisting',
            name='task_creator',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskDepend',
        ),
        migrations.DeleteModel(
            name='TaskListing',
        ),        
    ]
