# Generated by Django 3.1 on 2022-07-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0100_auto_20220623_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bounty',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Blocked'), (2, 'Available'), (3, 'Claimed'), (4, 'Done'), (5, 'In review')], default=2),
        ),
    ]
