# Generated by Django 3.1 on 2022-08-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0102_auto_20220728_1549'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "SELECT setval(pg_get_serial_sequence('\"work_challenge\"','id'), coalesce(max(\"id\"), 1), max(\"id\") IS NOT null) FROM \"work_challenge\";",
                "SELECT setval(pg_get_serial_sequence('\"work_challengelisting\"','id'), coalesce(max(\"id\"), 1), max(\"id\") IS NOT null) FROM \"work_challengelisting\";",
                "SELECT setval(pg_get_serial_sequence('\"work_challenge_depend\"','id'), coalesce(max(\"id\"), 1), max(\"id\") IS NOT null) FROM \"work_challenge_depend\";",
                "SELECT setval(pg_get_serial_sequence('\"work_productchallenge\"','id'), coalesce(max(\"id\"), 1), max(\"id\") IS NOT null) FROM \"work_productchallenge\";"
            ],
            reverse_sql=[],
        )
    ]
