# Generated by Django 3.1 on 2022-06-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0014_auto_20220618_2252'),
        ('points_and_payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributoraccountcredit',
            name='task_claim',
        ),
        migrations.RemoveField(
            model_name='productaccountdebit',
            name='task_claim',
        ),
        migrations.RemoveField(
            model_name='productaccountreservation',
            name='task_claim',
        ),
        migrations.AddField(
            model_name='contributoraccountcredit',
            name='bounty_claim',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matching.bountyclaim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productaccountdebit',
            name='bounty_claim',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matching.bountyclaim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productaccountreservation',
            name='bounty_claim',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='matching.bountyclaim'),
            preserve_default=False,
        ),
    ]
