# Generated by Django 3.1 on 2021-03-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20210304_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='depth',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
