# Generated by Django 3.1 on 2021-03-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20210304_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='person',
        ),
    ]
