# Generated by Django 3.1 on 2021-03-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_remove_comment_person'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
