# Generated by Django 3.1 on 2021-03-04 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_comment2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
