# Generated by Django 3.1 on 2021-03-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0013_auto_20210304_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment2',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
