# Generated by Django 3.1 on 2022-06-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0046_personpreferences'),
        ('comments', '0022_user_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskComment',
            new_name='ChallengeComment',
        ),
    ]
