# Generated by Django 3.1 on 2022-04-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('event_type', models.IntegerField(choices=[(0, 'Task Claimed'), (1, 'Task Comment'), (2, 'Submission Approved'), (3, 'Submission Rejected'), (4, 'Bug Rejected'), (5, 'Idea Rejected'), (6, 'Bug Created'), (7, 'Idea Created'), (8, 'Bug Created For Members'), (9, 'Idea Created For Members'), (10, 'Task Status Changed'), (11, 'Task In Review'), (12, 'Generic Comment'), (13, 'Task Submitted'), (14, 'Task Ready To Review'), (15, 'Task Delivery Attempt Created'), (16, 'Contributor Left Task')], primary_key=True, serialize=False)),
                ('permitted_params', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=400)),
                ('template', models.CharField(max_length=4000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
