# Generated by Django 3.1 on 2021-02-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_auto_20210121_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name_plural': 'Organisations'},
        ),
    ]
