# Generated by Django 3.1 on 2021-03-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_auto_20210216_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationperson',
            name='right',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Product Admin'), (2, 'Product Manager'), (3, 'Contributor'), (4, 'Super Admin')], default=0),
        ),
    ]
