# Generated by Django 3.1 on 2021-03-29 13:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0026_socialaccount'),
        ('commercial', '0009_auto_20210315_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('username', models.CharField(max_length=39, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='\n                                            - username may only contain alphanumeric characters or hyphens.\n                                            - username cannot have multiple consecutive hyphens.\n                                            - username cannot begin or end with a hyphen.\n                                        ', regex='^(?!-)(?!.*--)[a-zA-Z\\d)-]+(?<!-)$')])),
                ('organisation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.organisation')),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
