# Generated by Django 3.1 on 2021-03-29 14:40

import commercial.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0067_product_is_private'),
        ('talent', '0026_socialaccount'),
        ('commercial', '0010_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='ProductOwner',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='username',
            name='username',
            field=models.CharField(max_length=39, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username may only contain alphanumeric characters or hyphens & cannot have multiple consecutive hyphens & cannot begin or end with a hyphen', regex='^(?!-)(?!.*--)[a-zA-Z\\d)-]+(?<!-)$'), commercial.validators.validate_reserved_words]),
        ),
    ]
