# Generated by Django 3.1 on 2021-03-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0011_auto_20210329_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='username',
            name='person',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
    ]
