# Generated by Django 3.1 on 2021-03-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0012_auto_20210330_1321'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='username_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.username'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Username',
        ),
    ]
