# Generated by Django 3.1 on 2021-06-15 12:27

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0013_auto_20210330_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='username_ptr',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='uuid',
        ),
        migrations.AddField(
            model_name='organisation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='username',
            field=models.CharField(default='', max_length=39, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username may only contain letters and numbers', regex='^[a-z0-9]*$')]),
        ),
    ]
