# Generated by Django 3.1 on 2021-06-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0032_user_model'),
        ('commercial', '0014_user_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='person',
        ),
        migrations.RemoveField(
            model_name='organisationperson',
            name='person',
        ),
        migrations.RemoveField(
            model_name='productowner',
            name='person',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='customer_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.person'),
        ),
        migrations.AddField(
            model_name='organisationperson',
            name='customer_person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='talent.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productowner',
            name='customer_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.person'),
        ),
    ]
