# Generated by Django 3.1 on 2021-06-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0015_user_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraccount',
            old_name='customer_person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='organisationperson',
            old_name='customer_person',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='productowner',
            old_name='customer_person',
            new_name='person',
        ),
    ]
