# Generated by Django 3.1 on 2021-06-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0016_user_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productowner',
            name='organisation',
        ),
        migrations.AddField(
            model_name='productowner',
            name='organisation_rel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercial.organisation'),
        ),
    ]
