# Generated by Django 3.1 on 2021-12-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0019_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationperson',
            name='right',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Product Admin'), (2, 'Product Manager'), (3, 'Contributor')], default=0),
        ),
    ]
